controllers:
    resource:
        path: ../src/Controller/
        namespace: App\Controller
    type: attribute
# index:
#     path: /pruebas
#     controller: App\Controller\DefaultController::index

# index1:
#     path: /
#     controller: App\Controller\ProyectoController::index

# indexUno:
#     path: /uno
#     controller: App\Controller\DefaultController::index1

# indexDos:
#     path: /dos
#     controller: App\Controller\DefaultController::index2    